### PR TITLE
Fix negative identifier in cursor

### LINKED ISSUE #87: Replace negative identifier in cursor with _
```sql
CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    bio VARCHAR(1000) NOT NULL DEFAULT '',
    image VARCHAR(255) NOT NULL DEFAULT ''
);

selectByUsername:
SELECT email, username, bio, image
FROM users
WHERE username = :username;
```

```text
kotlin.IllegalStateException: ERROR:  syntax error at or near "-"
LINE 1: DECLARE cursor-226892384 CURSOR FOR SELECT email, username, ...
```

### PR DESCRIPTION
**Pull request by hfhbd**
Fixes #87

### CODE REVIEW

**Comment by hfhbd** [comment]
@nomisRev What else do you think? Sure, we could check if id is negative instead.

File: postgres-native-sqldelight-driver/src/commonMain/kotlin/app/softwork/sqldelight/postgresdriver/PostgresNativeDriver.kt [hunk 1]
```diff
@@ -111,7 +111,7 @@ public class PostgresNativeDriver(private var conn: CPointer<PGconn>) : SqlDrive
         parameters: Int,
         binders: (SqlPreparedStatement.() -> Unit)?
     ): QueryResult.Value<R> {
-        val cursorName = if (identifier == null) "myCursor" else "cursor$identifier"
+        val cursorName = if (identifier == null) "myCursor" else "cursor${identifier.toString().replace("-", "_")}"
```
Comment (nomisRev) [inline postgres-native-sqldelight-driver/src/commonMain/kotlin/app/softwork/sqldelight/postgresdriver/PostgresNativeDriver.kt:114]: I think the only downside here is that `replace` loops over all the `Char` in the `String`, perhaps a bit micro-optimisation but the function below is simply enough without complicating the code a lot.

```kotlin
private fun Int.asCursorIdentifier(): String  =
    if(this < 0) "_${toString().substring(1)}" else toString()
```

Changing the snippet to:

`"cursor${identifier.asCursorIdentifier()}"`

Comment (hfhbd) [reply postgres-native-sqldelight-driver/src/commonMain/kotlin/app/softwork/sqldelight/postgresdriver/PostgresNativeDriver.kt]: thanks, was unaware of the loop!
